version: '3.8'

services:
  cti-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
      - ./exports:/app/exports
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  data-collector:
    build: .
    command: python background_jobs/cron_update_db.py
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - cti-bot
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  redis_data:

